### ISSUE TITLE
Can't insert into hstore column in Postgresql

### ISSUE THREAD

**Issue by billrobertson42** [krisajenkins/yesql#59]
The pgjdbc driver supports maps as input/output for hstore columns. Selecting data through yesql fails, but trying to insert (and update I assume) fails. BTW, I think yesql is great. Thanks for the hard work.

e.g. 

    # create extension if not exist hstore;
    # create table hstore_table (id int primary key, hstore_col hstore default '');
    CREATE TABLE
    # insert into hstore_table (id, hstore_col) values (1, 'a=>b');
    INSERT 0 1
    # select * from hstore_table;
     id | hstore_col 
     ----+------------
      1 | "a"=>"b"
    (1 row)

The yesql file...

    --name: get-something-with-hstore-column
    SELECT id, hstore_col from hstore_table;

    --name: add-something-to-hstore-table!
    INSERT INTO  hstore_table (id, hstore_col) values (:id :hstore_col);

Selecting works great.

    => (dbxl :master conn (get-something-with-hstore-column conn))
    DEBUG jdbc.sqltiming -  clojure.java.jdbc$db_query_with_resultset$run_query_with_params__406.invoke(jdbc.clj:786)
    7. SELECT id, hstore_col from hstore_table; 
     {executed in 1 msec}
    ({:hstore_col {"a" "b"}, :id 1})

However, calling the add-someting function bombs.

    (add-something-to-hstore-table! conn 27 {"foo" "bar2"})
    2015-02-08;17:32:53.946 ERROR jdbc.audit - 6. PreparedStatement.setObject(2, ["foo" "bar2"])
        org.postgresql.util.PSQLException: Can't infer the SQL type to use for an instance of clojure.lang.MapEntry. Use setObject() with an explicit Types value to specify the type to use.
    	at org.postgresql.jdbc2.AbstractJdbc2Statement.setObject(AbstractJdbc2Statement.java:1916) ~[postgresql-9.3-1102-jdbc41.jar:na]
    	at org.postgresql.jdbc3g.AbstractJdbc3gStatement.setObject(AbstractJdbc3gStatement.java:36) ~[postgresql-9.3-1102-jdbc41.jar:na]
    	at org.postgresql.jdbc4.AbstractJdbc4Statement.setObject(AbstractJdbc4Statement.java:47) ~[postgresql-9.3-1102-jdbc41.jar:na]
    	at net.sf.log4jdbc.PreparedStatementSpy.setObject(PreparedStatementSpy.java:971) ~[log4jdbc-1.2.jar:na]
    	at clojure.java.jdbc$fn__286.invokePrim(jdbc.clj:338) [classes/:na]
    	at clojure.java.jdbc$fn__286.invoke(jdbc.clj) [classes/:na]
    	at clojure.java.jdbc$fn__269$G__264__278.invoke(jdbc.clj:325) [classes/:na]
    	at clojure.java.jdbc$set_parameters$fn__339.invoke(jdbc.clj:463) [classes/:na]
    	at clojure.core$map_indexed$mapi__6395$fn__6396.invoke(core.clj:6690) [clojure-1.6.0.jar:na]
    	at clojure.lang.LazySeq.sval(LazySeq.java:40) [clojure-1.6.0.jar:na]
    	at clojure.lang.LazySeq.seq(LazySeq.java:49) [clojure-1.6.0.jar:na]
    	at clojure.lang.RT.seq(RT.java:484) [clojure-1.6.0.jar:na]
    	at clojure.core$seq.invoke(core.clj:133) [clojure-1.6.0.jar:na]
    	at clojure.core$dorun.invoke(core.clj:2855) [clojure-1.6.0.jar:na]
    	at clojure.java.jdbc$set_parameters.invoke(jdbc.clj:462) [classes/:na]
    	at clojure.java.jdbc$db_do_execute_prepared_statement.invoke(jdbc.clj:725) [classes/:na]
    	at clojure.java.jdbc$db_do_prepared.doInvoke(jdbc.clj:749) [classes/:na]
    	at clojure.lang.RestFn.invoke(RestFn.java:464) [clojure-1.6.0.jar:na]
    	at clojure.java.jdbc$execute_BANG_$execute_helper__421.invoke(jdbc.clj:851) [classes/:na]
    	at clojure.java.jdbc$execute_BANG_.doInvoke(jdbc.clj:854) [classes/:na]
    	at clojure.lang.RestFn.invoke(RestFn.java:425) [clojure-1.6.0.jar:na]
    	at yesql.types$execute_handler.invoke(types.clj:45) [classes/:na]

**Comment by arivi** [comment]
With 0.5 you could do something like this:
```clojure
(defn to-hstore [m]
  (doto (PGobject.)
    (.setType "hstore")
    (.setValue
      (apply str
             (interpose ", "
                        (for [[k v] m]
                          (format "\"%s\"=>\"%s\"" (name k) v)))))))

(extend-type clojure.lang.IPersistentMap
  jdbc/ISQLParameter
  (set-parameter [val stmt ix]
    (.setObject stmt ix (to-hstore val))
    )
  )
```
And calling it (with the 0.5 -syntax) would look like this:
```clojure
(add-something-to-hstore-table! {:hstore-column {:foo "bar}})
```
This will break if you need keys or values with double quotes or backslashes in them, so you should add escaping if needed.

For 0.4 this didn't seem quite as simple, because it seems that it doesn't try setting the parameter as a map (clojure.lang.IPersistentMap) but as map entries (clojure.lang.MapEntry).

**Comment by liusong1111** [comment]
@arivi 

for postgresql,  clj-postgresql library does this already. 
How to integrate it, or provides a pluggable solution:

```sql
-- name: create-users<!
-- db: postgresql , table: users(name varchar, labels: text[])
insert into users(name,labels) values(:name, :labels::text[])
```

```clojure
(create-users "sliu" ["aa" "bb"])
```

`::text[]` indicates using a plugin to generate sql. Depending on db dialect, it chooses clj-postgresql or something else?
